export const cardsData = [
  {
    id: 1,
    category: "Priority DM",
    categoryMeta: "2 days reply",
    title: "Book me to speak at your event",
    description: "Inspiring talks for professionals and students",
    price: null,
    originalPrice: null,
    isFree: true,
    rating: null,
    type: "dm",
  },
  {
    id: 2,
    category: "Video meeting",
    categoryMeta: "30 mins",
    title: "How to Start as a Freelance UX/UI Designer",
    description: "Kickstart Your Freelance UX/UI Career",
    price: 199,
    originalPrice: 299,
    isFree: false,
    rating: 5,
    type: "call",
  },
  {
    id: 3,
    category: "Video meeting",
    categoryMeta: "15 mins",
    title: "Quick call",
    description: "15mins Design Clarity Call",
    price: 230,
    originalPrice: 300,
    isFree: false,
    rating: 5,
    type: "call",
  },
  {
    id: 4,
    category: "Digital Product",
    categoryMeta: null,
    title: "3 resume templates — Figma",
    description: "Stand Out with Designer-Grade Resume Templates!",
    price: 149,
    originalPrice: 249,
    isFree: false,
    rating: null,
    type: "digital",
  },
  {
    id: 5,
    category: "Course",
    categoryMeta: "8 modules",
    title: "UX Design from Zero to Hero",
    description: "Complete UX curriculum for absolute beginners",
    price: 999,
    originalPrice: 1499,
    isFree: false,
    rating: 5,
    type: "courses",
  },
  {
    id: 6,
    category: "Package",
    categoryMeta: "4 sessions",
    title: "Portfolio Review Bundle",
    description: "Deep-dive reviews across 4 dedicated sessions",
    price: 799,
    originalPrice: 1200,
    isFree: false,
    rating: null,
    type: "packages",
  },
];
